# Generated by Django 5.1.5 on 2025-01-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_agree',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Чекбокс согласие на условия'),
        ),
    ]
