# Generated by Django 5.1.5 on 2025-01-30 06:12

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalIllness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Наименование заболеваний')),
            ],
            options={
                'verbose_name': 'Тип заболевания',
                'verbose_name_plural': 'Тип заболевания',
            },
        ),
        migrations.CreateModel(
            name='DemographicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=300, null=True, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=300, null=True, verbose_name='Город')),
                ('position', models.CharField(blank=True, max_length=300, null=True, verbose_name='Образование')),
                ('ethnicity', models.CharField(blank=True, max_length=300, null=True, verbose_name='Этническая принадлежность')),
                ('type_health_insurance', models.CharField(blank=True, max_length=300, null=True, verbose_name='Вид медицинской страховки')),
                ('biography', models.CharField(blank=True, max_length=300, null=True, verbose_name='Биография')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_demographic_data', to=settings.AUTH_USER_MODEL, verbose_name='Демографические данные пользователя')),
            ],
            options={
                'verbose_name': 'Демографические данные пользователя',
                'verbose_name_plural': 'Демографические данные пользователя',
            },
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название интереса')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_insterest', to=settings.AUTH_USER_MODEL, verbose_name='Интерес пользователя')),
            ],
            options={
                'verbose_name': 'Интерес пользователя',
                'verbose_name_plural': 'Интерес пользователя',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(verbose_name='Моя история болезни')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('still_ongoing', models.DateField(auto_now_add=True, null=True, verbose_name='Все еще продолжается')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_medical_history', to=settings.AUTH_USER_MODEL, verbose_name='История болезни пользователя')),
                ('medical_illness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_illness', to='users.medicalillness', verbose_name='Тип заболевания')),
            ],
            options={
                'verbose_name': 'История болезни пользователя',
                'verbose_name_plural': 'История болезни пользователя',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(verbose_name='Название заметки')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to=settings.AUTH_USER_MODEL, verbose_name='Заметки пользователя')),
            ],
            options={
                'verbose_name': 'Заметки пользователя',
                'verbose_name_plural': 'Заметки пользователя',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
