# Generated by Django 5.1.5 on 2025-01-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='interests',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='medicalhistory',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='notes',
            managers=[
            ],
        ),
    ]
