# Generated by Django 5.1.5 on 2025-02-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_diseasehistorydaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
