# Generated by Django 5.1.5 on 2025-02-14 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_is_activate_demographicdata_w_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demographicdata',
            old_name='w',
            new_name='is_activate',
        ),
    ]
