# Generated by Django 5.1.5 on 2025-02-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_w_demographicdata_is_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='is_activate',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Активируется'),
        ),
    ]
