# Generated by Django 5.1.5 on 2025-02-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_followers_is_activate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demographicdata',
            options={'verbose_name': 'Демографические данные пользователя', 'verbose_name_plural': '1. Демографические данные пользователя'},
        ),
        migrations.AlterModelOptions(
            name='diseasehistorydaily',
            options={'verbose_name': 'История пользователя ежедневно', 'verbose_name_plural': '6. История пользователя ежедневно'},
        ),
        migrations.AlterModelOptions(
            name='followers',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': '7. Подписки'},
        ),
        migrations.AlterModelOptions(
            name='interests',
            options={'verbose_name': 'Интерес пользователя', 'verbose_name_plural': '5. Интерес пользователя'},
        ),
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'verbose_name': 'История болезни пользователя', 'verbose_name_plural': '3. История болезни пользователя'},
        ),
        migrations.AlterModelOptions(
            name='medicalillness',
            options={'verbose_name': 'Тип заболевания', 'verbose_name_plural': '2. Тип заболевания'},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Заметки пользователя', 'verbose_name_plural': '4. Заметки пользователя'},
        ),
    ]
