# Generated by Django 5.1.5 on 2025-02-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_demographicdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicdata',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Активируется'),
        ),
        migrations.AlterField(
            model_name='diseasehistorydaily',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Активируется'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Активируется'),
        ),
        migrations.AlterField(
            model_name='interests',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Активируется'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Активируется'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Активируется'),
        ),
    ]
