# Generated by Django 5.1.5 on 2025-02-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_demographicdata_is_activate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicdata',
            name='biography',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='city',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Этническая принадлежность'),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='position',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='region',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='type_health_insurance',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Вид медицинской страховки'),
        ),
        migrations.AlterField(
            model_name='interests',
            name='name',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Название интереса'),
        ),
        migrations.AlterField(
            model_name='medicalillness',
            name='name',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Наименование заболеваний'),
        ),
    ]
